### ISSUE TITLE
 Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {myDomain.MyProject/mingsin.fzxing.CaptureActivity}; have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by chunhunghan** [trevorwang/flutter-zxing#4]
Example work great. But I have trouble to use this plugin in my project. 
Could you provide correct AndroidManifest.xml setting example.
I have tested with the following items but no luck.

	<activity android:name="/mingsin.fzxing.CaptureActivity"/>
	<activity android:name=".mingsin.fzxing.CaptureActivity"/>
	<activity android:name="myDomin.MyProject.mingsin.fzxing.CaptureActivity"/>

my sample AndroidManifest.xml

	<manifest xmlns:android="http://schemas.android.com/apk/res/android"
		package="myDomain.myProject">

		<uses-permission android:name="android.permission.INTERNET"/>

		
		<application
			android:name="io.flutter.app.FlutterApplication"
			android:label="myProject"
			android:usesCleartextTraffic="true"
			android:icon="@mipmap/ic_launcher">

			<activity
				android:name=".MainActivity"
				android:launchMode="singleTop"
				android:theme="@style/LaunchTheme"
				android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
				android:hardwareAccelerated="true"
				android:windowSoftInputMode="adjustResize">
				
				<meta-data
					android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
					android:value="true" />
				<intent-filter>
					<action android:name="android.intent.action.MAIN"/>
					<category android:name="android.intent.category.LAUNCHER"/>
				</intent-filter>
			</activity>

			
			<activity android:name="/mingsin.fzxing.CaptureActivity"/>
		</application>
	</manifest>

**Comment by trevorwang** [comment]
It should be `<activity android:name="/mingsin.fzxing.CaptureActivity"/>`

**Comment by trevorwang** [comment]
The plugin will handle the activity registration automatically. You don't need to add them in your project.

![Screen Shot 2019-05-22 at 1 58 31 PM](https://user-images.githubusercontent.com/121966/58150681-f98b3080-7c99-11e9-8188-d2955ad2c5ca.png)

**Comment by chunhunghan** [comment]
Thank you for your kind support. 
After long struggling,
I have to delete build folder after add kotlin setting. 
VSCode and Android Studio both have the same problem.
This is an amazing project.
